-d C:\Users\james\OneDrive\verilog\blueplate\arduino_io_4b\arduino_io_4b_tang\impl\gwsynthesis\arduino_io_4b_tang.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\james\OneDrive\verilog\blueplate\arduino_io_4b\arduino_io_4b_tang\src\tangnano20k.cst
-cfg C:\Users\james\OneDrive\verilog\blueplate\arduino_io_4b\arduino_io_4b_tang\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
